### ISSUE TITLE
hostPath volumes not working with VMware Fusion Pro 11.0.3

### ISSUE THREAD

**Issue by wittlesouth** [machine-drivers/docker-machine-driver-vmware#21]
I recently tried upgrading versions in my OS X development environment, and ran into issues starting a MySQL virtual machine due to issues accessing a hostPath persistent volume. The configuration I have works fine when using the vmwarefusion driver, but fails with the VMware driver. 

minikube version: 1.0.1
kubernetes version: 1.14.1
vmware fusion version: 11.0.3 pro

The persistent volume is created with the following yams:

```
# Create local volumes for development MySQL instance
#
# Persistent Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dev-db
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  storageClassName: local-dev-db
  hostPath:
    path: /Users/eric/Development/wsv/localdev/dev-db-files
```

If I use the vmwarefusion driver with the configuration, mysql starts and runs fine. If I use the vmware driver, the mysql container errors during initialization with issues creating / accessing files in the data directory (which should be the persistent volume created above). Let me know what else is needed for debugging.
